uncurl_app/views.py
import json
from multiprocessing.dummy import Process
import os
import uuid

from flask import render_template, request, redirect, send_from_directory, url_for, Blueprint, current_app
from werkzeug.utils import secure_filename

import numpy as np
import uncurl

from .cache import cache

from .generate_analysis import generate_uncurl_analysis, get_progress
from .data_stats import Summary

views = Blueprint('views', __name__, template_folder='templates')

def load_upload_data(request_files, request_form, path=None):
    data_paths = []
    gene_paths = []
    shapes = []
    output_filenames = []
    data_names = []
    for key, f in request_files.items():
        if 'fileinput' in key:
            input_id = key.split('-')[1]
            output_filename = secure_filename(f.filename)
            if output_filename == '':
                return
            output_filenames.append(output_filename)
            # allow for mtx input data
            input_type = request_form['inputtype-{0}'.format(input_id)]
            if output_filename.endswith('.mtx.gz') or output_filename.endswith('.mtx'):
                input_type = 'sparse'
            if input_type == 'dense':
                data_filename = 'data_{0}.txt'.format(input_id)
                if output_filename.endswith('.gz'):
                    data_filename = 'data_{0}.txt.gz'.format(input_id)
                data_path = os.path.join(path, data_filename)
                f.save(data_path)
            elif input_type == 'sparse':
                data_filename = 'data_{0}.mtx'.format(input_id)
                if output_filename.endswith('.mtx.gz'):
                    data_filename = 'data_{0}.mtx.gz'.format(input_id)
                data_path = os.path.join(path, data_filename)
                f.save(data_path)
            shape = request_form['data_shape-{0}'.format(input_id)]
            shapes.append(shape)
            # try to find gene names
            data_paths.append(data_path)
            try:
                gene_file = request_files['genenames-{0}'.format(input_id)]
                print(gene_file)
                gene_output_file = load_gene_names(gene_file, path, input_id)
                gene_paths.append(gene_output_file)
            except Exception as e:
                print(e)
                print('failed to get gene names')
                gene_paths.append(None)
            data_name = request_form['data_name-{0}'.format(input_id)]
            if len(data_name) == 0:
                data_name = str(input_id)
            data_names.append(data_name)
    init = None
    return data_paths, gene_paths, data_names, init, shapes


def load_gene_names(f, path=None, index=1):
    gene_filename = secure_filename(f.filename)
    gene_output_path = os.path.join(path, 'gene_names_{0}.txt'.format(index))
    compression = None
    if gene_filename.endswith('.gz'):
        compression = 'gzip'
    if gene_filename.endswith('genes.csv') or gene_filename.endswith('genes.csv.gz'):
        print('processing genes.csv')
        import pandas as pd
        data = pd.read_csv(f, compression=compression)
        try:
            gene_names = data['gene_name']
            gene_names.to_csv(gene_output_path, header=None, index=None)
        except Exception as e:
            print(e)
            f.seek(0)
            f.save(gene_output_path)
    elif gene_filename.endswith('features.tsv') or gene_filename.endswith('features.tsv.gz'):
        print('processing features.tsv')
        import pandas as pd
        data = pd.read_csv(f, sep='\t', header=None, compression=compression)
        try:
            gene_names = data[1]
            gene_names.to_csv(gene_output_path, header=None, index=None)
        except Exception as e:
            print(e)
            f.seek(0)
            f.save(gene_output_path)
    elif gene_filename.endswith('.gz'):
        # gunzip the file
        import subprocess
        base_file_path = os.path.join(path, gene_filename)
        f.save(base_file_path)
        subprocess.call(['gunzip', base_file_path])
        f = open(base_file_path)
        gene_filename = gene_filename[:-3]
        f.save(gene_output_path)
    else:
        f.save(gene_output_path)
    return gene_output_path

@views.route('/help')
def help():
    return render_template('help.html')

@views.route('/state_estimation')
@cache.cached()
def state_estimation():
    return render_template('state_estimation.html')

@views.route('/state_estimation/input', methods=['POST'])
def state_estimation_input():
    user_id = str(uuid.uuid4())
    if 'username' in request.form:
        if len(request.form['username']) > 0:
            # make username a safe string
            keep_chars = set(['-', '_', ' '])
            username = request.form['username'].strip()[:25]
            username = ''.join([c for c in username if c.isalnum() or (c in keep_chars)])
            user_id = user_id + '-' + username
    base_path = os.path.join(current_app.config['USER_DATA_DIR'], user_id)
    os.makedirs(base_path)
    # save request.form
    with open(os.path.join(base_path, 'inputs.json'), 'w') as f:
        f.write(json.dumps(request.form))
    request_file = request.files
    request_form = request.form
    # use batch effect correction button 
    use_batch_correction = False
    if 'use_batch_correction' in request.form:
        use_batch_correction = request.form['use_batch_correction']
    data_paths, gene_paths, output_filenames, init, shapes = load_upload_data(request_file, request_form, base_path)
    P = Process(target=state_estimation_preproc, args=(user_id, base_path, data_paths, gene_paths, output_filenames, init,
        shapes,
        use_batch_correction))
    P.start()
    return redirect(url_for('views.state_estimation_result', user_id=user_id))

@views.route('/state_estimation/results/<user_id>/start', methods=['POST'])
def state_estimation_start(user_id):
    """
    Actually start the process of state estimation.

    This saves a file called 'params.json' in /tmp/uncurl/<user_id>
    containing all parameters used in state estimation.
    """
    path = os.path.join(current_app.config['USER_DATA_DIR'], user_id)
    gene_names_file = os.path.join(path, 'gene_names.txt')
    if not os.path.exists(gene_names_file):
        gene_names_file = None
    # TODO: deal with init here - make note if it's qualitative or
    # quantitative
    # run qualNorm???
    init_path= os.path.join(path, 'init.txt')
    if not os.path.exists(init_path):
        init_path = None
    # load json params
    with open(os.path.join(path, 'preprocess.json')) as f:
        preprocess = json.load(f)
    for key in request.form.keys():
        preprocess[key] = request.form[key]
    # params.json contains all input parameters to the state estimation, as well as all stats from preprocess.json.
    with open(os.path.join(path, 'params.json'), 'w') as f:
        json.dump(preprocess, f)
    P = Process(target=state_estimation_thread, args=(user_id, gene_names_file, init_path, path, preprocess, current_app.config.copy()))
    P.start()
    return redirect(url_for('views.state_estimation_result', user_id=user_id))


@views.route('/state_estimation/results/<user_id>/')
def state_estimation_result(user_id):
    path = os.path.join(current_app.config['USER_DATA_DIR'], user_id)
    if os.path.exists(os.path.join(path, 'sc_analysis.json')):
        return redirect(url_for('interaction_views.view_plots', user_id=user_id))
    elif os.path.exists(os.path.join(path, 'preprocess.json')):
        uncurl_is_running = os.path.exists(os.path.join(path, 'submitted'))
        current_task = 'None'
        time_remaining = 'Unknown'
        with open(os.path.join(path, 'preprocess.json')) as f:
            preprocess = json.load(f)
        try:
            with open(os.path.join(path, 'read_count_hist_data.json')) as f:
                read_count_hist_data = f.read()
            with open(os.path.join(path, 'gene_count_hist_data.json')) as f:
                gene_count_hist_data = f.read()
            with open(os.path.join(path, 'gene_mean_hist_data.json')) as f:
                gene_mean_hist_data = f.read()
        except:
            summary = Summary(None, None, base_path=path)
            read_count_hist_data, gene_count_hist_data, gene_mean_hist_data = summary.generate_plotly_jsons()
        if uncurl_is_running:
            # get running time information (highly approximate)
            current_task, time_remaining = get_progress(path)
            # update with actual input parameters
            with open(os.path.join(path, 'params.json')) as f:
                preprocess.update(json.load(f))
        uncurl_has_error = False
        if time_remaining == 'error':
            # TODO: if there is an error here...
            uncurl_has_error = True
        return render_template('state_estimation_user.html',
                user_id=user_id, has_preview=True,
                uncurl_is_done=False,
                uncurl_is_running=uncurl_is_running,
                uncurl_has_error=uncurl_has_error,
                read_count_hist_data=read_count_hist_data,
                gene_count_hist_data=gene_count_hist_data,
                gene_mean_hist_data=gene_mean_hist_data,
                current_task=current_task,
                time_remaining=time_remaining,
                **preprocess)
    elif os.path.exists(os.path.join(path, 'error.txt')):
        error_txt = ''
        with open(os.path.join(path, 'error.txt')) as f:
            error_txt = f.read()
        return error(error_txt, 404)
    else:
        return render_template('state_estimation_user.html',
                user_id=user_id, uncurl_is_running=False,
                uncurl_is_done=False,
                has_result=False)

# this gzips the directory and returns a download
@views.route('/<x>/results/<user_id>/download_all')
def state_estimation_download_all(x, user_id):
    if x!='test':

uncurl_app/templates/data_download.html
{% extends "base.html" %}

{% block head %}
{{super()}}
{% endblock %}

{% block content %}

<div class="container container-main" role="main">
    <h3>Data downloads for query id {{ user_id }}</h3>

    <a type="button" class="btn btn-primary btn-md" href="{{ url_for('views.state_estimation_download_all', x=test_or_user, user_id=user_id) }}">Download all as zip</a>

    <!--have a list of downloads -->
    <ul>
        {% for element in files %}
        <li><a href="{{ url_for('views.state_estimation_file', x=test_or_user, user_id=user_id, filename=element) }}">{{ element }}</a></li>
        {% endfor %}
    </ul>

</div>

{% endblock %}

uncurl_app/templates/db_query_genes.html
{% extends "base.html" %}

{% block head %}

{{ super() }}

<script src="{{ url_for('static', filename='jquery-3.3.1.min.js') }}"></script>

<link rel="stylesheet" href="{{ url_for('static', filename='state_estimation_style.css') }}" type="text/css"/>

<script>

var cache = {};
cache.enrichr = {};
var tree = {};
var id_to_name = {};

// toggles visibility of the bottom-left gene query view
// 'toggle' is a jquery method that changes the visibility of the element.
function toggle_query_visibility() {
    var views = ['cellmarker_view', 'cellmesh_view', 'cellmesh_anatomy_view', 'go_view', 'kegg_view'];
    var value = $('#database_select').val();
    var view_select = value + '_view';
    for (var i in views) {
        if (views[i] == view_select) {
            $('#'+views[i]).toggle(true);
        } else {
            $('#'+views[i]).toggle(false);
        }
    }
};

function set_enrichr_results(data, query) {
    // create table
    results_view = $('#' + query + '_results');
    results_view.empty();
    var table = $('<table>');
    var header = $('<tr>');
    for (var j = 0; j<data[0].length; j++) {
        header.append('<th>'+data[0][j]+'</th>');
    }
    table.append(header);
    for (var i = 1; i<data.length; i++) {
        var row = $('<tr>');
        for (var j = 0; j<data[i].length; j++) {
            row.append('<td>'+data[i][j]+'</td>');
        }
        table.append(row);
    }
    results_view.append(table);
}; 

function update_gene_query(query) {
    // query is a string that can be 'enrichr', 'cellmarker', etc...
    var input_array = $('#gene-set-query-form').serializeArray();
    var data = {};
    $(input_array).each(function(index, obj){
        data[obj.name] = obj.value;
    });
    console.log('update_gene_query');
    console.log(data);
    var key = JSON.stringify(data);
    if (cache.enrichr.hasOwnProperty(key)) {
        set_enrichr_results(cache.enrichr[key], query);
        return true;
    }
    results_view = $('#' + query + '_results');
    results_view.empty();
    results_view.append("<br>" + "Query in progress..." + '<img src="/static/ajax-loader.gif"/>');
    $.ajax({url: '/db_query/cell_info',
        type: "POST",
        data: data,
    }).done(function(results) {
        results_view.empty();
        if (results.startsWith('Error')) {
            results_view.append(results);
        } else {
            results = JSON.parse(results);
            cache.enrichr[key] = results;
            set_enrichr_results(results, query);
        }
    });
    return true;
};

window.onload = function() {
    toggle_query_visibility();

//    $.ajax({url: '/db_query/get_mesh_tree',
//        type: "GET",
//    }).done(function(results) {
//        console.log(results);
//        results = JSON.parse(results);
//        tree = results.tree;
//        id_to_name = results.id_to_name; 
//    });
};

</script>
{% endblock %}

{% block content %}
<div class="container container-main" role="main">
    <h4>Given a cell type, return all genes belonging to that cell type.</h4>
    <form id="gene-set-query-form">

        <!-- onchange: make the cellmarker view visible -->
        <div class="form-inline">
            <label for="database_select" data-toggle="tooltip" title="Which database to query for the given gene set. Current options are Enrichr and CellMarker.">Database:</label>
            <select class="form-control" id="database_select" name="database_select" style="width:200px; margin-top: 5px;" onchange="toggle_query_visibility();">
                <option value="cellmarker">CellMarker</option>
                <option value="cellmesh" selected>CellMeSH</option>
                <option value="cellmesh_anatomy">CellMeSH-Anatomy</option>
                <option value="kegg">KEGG</option>
            </select>
        </div>

        <div class="form-inline">
            <label for="mode">Mode:</label>
            <select class="form-control" id="mode" name="mode" style="width:200px; margin-top: 5px;">
                <option value="gene_papers" selected>Genes and papers</option>
                <option value="all_genes">Genes only</option>
            </select>
        </div>

        <div id="cellmarker_view" style="display:none;">
            <h5 data-toggle="tooltip" title="Query the CellMarker database for cell types matching the selected genes.">Query CellMarker with selected genes</h4>
            <div class="form-inline" style="margin-top: 5px; margin-bottom: 5px; width: 300px;">
                <label for="cellmarker_cell_type">Cell type:</label>
                <select class="form-control" id="cellmarker_cell_type" name="cellmarker_cell_type">
                    {% for cell in cell_lists['cellmarker'] %}
                    <option value="{{ cell }}">{{ cell }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-inline" style="margin-top: 5px; margin-bottom: 5px; width: 300px;">
                <label for="species" data-toggle="tooltip" title="Which species to query for cell types. Currently human and mouse are available.">Species:</label>
                <select class="form-control" id="species" name="species">
                    <option value="all" selected>All</option>
                    <option value="Human">Human</option>
                    <option value="Mouse">Mouse</option>
                </select>
            </div>
            <div class="form-inline" style="margin-top: 5px; margin-bottom: 5px; width: 300px;">
                <label for="cells_or_tissues">Cells or tissues:</label>
                <select class="form-control" id="cells_or_tissues" name="cells_or_tissues">
                    <option value="cells" selected>Cells</option>
                    <option value="tissues">Tissues</option>
                </select>
            </div>

            <button class="btn btn-default" id="cellmarker-submit" type="button" onclick="update_gene_query('cellmarker')">Submit CellMarker query</button>
            <div id="cellmarker_results"></div>
        </div>

        <div id="cellmesh_view" style="display:none;">
            <div class="form-inline" style="margin-top: 5px; margin-bottom: 5px; width: 500px;">
                <label for="cellmesh_cell_type">Cell type:</label>
                <select class="form-control" id="cellmesh_cell_type" name="cellmesh_cell_type">
                    <!-- TODO: load cell types -->
                    {% for cell in cell_lists['cellmesh'] %}
                    <option value="{{ cell }}">{{ cell }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-inline" style="margin-top: 5px; margin-bottom: 5px; width: 500px;">
                <label for="cellmesh_species" data-toggle="tooltip" title="Which species to query for cell types. Currently human and mouse are available.">Species:</label>
                <select class="form-control" id="cellmesh_species" name="cellmesh_species">
                    <!-- TODO: not available yet <option value="all" >All</option>-->
                    <option value="human" selected>Homo sapiens</option>
                    <option value="mouse">Mus musculus</option>
                    <option value="c_elegans">C. Elegans</option>
                </select>
                <label for="cellmesh_threshold" data-toggle="tooltip" title="Minimum number of citations">Threshold:</label>
                <input class="form-control" type="number" id="cellmesh_threshold" name="cellmesh_threshold" value="1" style="width: 50px;">
            </div>

            <button class="btn btn-default" id="cellmesh-submit" type="button" onclick="update_gene_query('cellmesh');">Submit CellMesh query</button>
            <div id="cellmesh_results"></div>
        </div>


        <div id="cellmesh_anatomy_view" style="display:none;">
            <div class="form-inline" style="margin-top: 5px; margin-bottom: 5px; width: 500px;">
                <label for="cellmesh_anatomy_cell_type">Cell type:</label>
                <select class="form-control" id="cellmesh_anatomy_cell_type" name="cellmesh_anatomy_cell_type">
                    {% for cell in cell_lists['cellmesh_anatomy'] %}
                    <option value="{{ cell }}">{{ cell }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-inline" style="margin-top: 5px; margin-bottom: 5px; width: 500px;">
                <label for="cellmesh_anatomy_species" data-toggle="tooltip" title="Which species to query for cell types. Currently human and mouse are available.">Species:</label>
                <select class="form-control" id="cellmesh_anatomy_species" name="cellmesh_anatomy_species">
                    <!-- TODO: not available yet <option value="all" >All</option>-->
                    <option value="human" selected>Homo sapiens</option>
                    <option value="mouse">Mus musculus</option>
                    <option value="c_elegans">C. Elegans</option>
                </select>
                <label for="cellmesh_anatomy_threshold" data-toggle="tooltip" title="Minimum number of citations">Threshold:</label>
                <input class="form-control" type="number" id="cellmesh_anatomy_threshold" name="cellmesh_anatomy_threshold" value="1" style="width: 50px;">
            </div>
            <button class="btn btn-default" id="cellmesh-anatomy-submit" type="button" onclick="update_gene_query('cellmesh_anatomy');">Submit CellMesh query</button>
            <div id="cellmesh_anatomy_results"></div>
        </div>


        <div id="kegg_view" style="display:none;">
            <div class="form-inline" style="margin-top: 5px; margin-bottom: 5px; width: 500px;">
                <label for="kegg_cell_type">Cell type:</label>
                <select class="form-control" id="kegg_cell_type" name="kegg_cell_type">
                    {% for cell in cell_lists['kegg'] %}
                    <option value="{{ cell }}">{{ cell }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-inline" style="margin-top: 5px; margin-bottom: 5px; width: 500px;">
                <label for="kegg_species" data-toggle="tooltip" title="Which species to query for cell types. Currently human and mouse are available.">Species:</label>
                <select class="form-control" id="kegg_species" name="kegg_species">
                    <!-- TODO: not available yet <option value="all" >All</option>-->
                    <option value="human" selected>Homo sapiens</option>
                    <option value="mouse">Mus musculus</option>
                </select>
            </div>
            <button class="btn btn-default" id="cellmesh-anatomy-submit" type="button" onclick="update_gene_query('kegg');">Submit CellMesh query</button>
            <div id="kegg_results"></div>
        </div>



    </form>
</div>
{% endblock %}

uncurl_app/templates/error.html
{% extends "base.html" %}

{% block content %}
<div class="container container-main" role="main">
    <h1>Internal Server Error</h1>

    <p> <pre>
    {{ msg }}
    </pre>
    </p>

    <p>Please leave an issue at <a href="https://github.com/yjzhang/uncurl_app">https://github.com/yjzhang/uncurl_app</a></p>


</div>
{% endblock %}

uncurl_app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container container-main" role="main">
    <h3>UNCURL-App</h3>

    <div style="margin-top: 20px; margin-bottom: 20px;">
        <a type="button" class="btn btn-lg btn-primary" href="/state_estimation">Upload new dataset</a>
        <a type="button" class="btn btn-lg btn-primary" href="/data">View existing datasets</a>
        <a type="button" class="btn btn-lg btn-primary" href="/help">Help</a>
    </div>

    <p>UNCURL-App is a unified framework for interactively analyzing single-cell RNA-seq data. It is based on UNCURL for data preprocessing and clustering. It can be used to perform a variety of tasks such as:</p>

    <ul>
        <li>Preprocessing</li>
        <li>Clustering</li>
        <li>Dimensionality reduction</li>
        <li>Differential expression</li>
        <li>Interactive data analysis and visualization</li>
    </ul>

    <p><b>If your data is smaller than 150MB, you can use the server at <a href="https://uncurl.cs.washington.edu">uncurl.cs.washington.edu</a>. Otherwise, you should use the <a href="https://hub.docker.com/repository/docker/ayuezhang27/uncurl-app">Docker image</a>.</b></p>

    <!-- TODO: help page link here? Make a decision tree - how big is your data? If your  -->

    <!--<div> 

        

        </div> -->

    <p><a type="button" class="btn btn-default btn-md" href="https://github.com/yjzhang/uncurl_app">Source code (web app)</a></p>
    <p><a type="button" class="btn btn-default btn-md" href="https://github.com/yjzhang/uncurl_python">Source code (UNCURL)</a></p>

    <p>Citation:</p> 
    <p>Zhang, Yue*, Shunfu Mao*, Sumit Mukherjee, Sreeram Kannan, and Georg Seelig. “UNCURL-App: Interactive Database-Driven Analysis of Single Cell RNA Sequencing Data.” BioRxiv, April 16, 2020, 2020.04.15.043737. https://doi.org/10.1101/2020.04.15.043737.</p>

    <!-- TODO: update figure to use the paper figure 1??? -->

    <img src="{{ url_for('static', filename='ClusterWorkflowUNCURL.jpg') }}" height="400">

</div>
{% endblock %}

uncurl_app/templates/lineage.html
{% extends "clustering.html" %}

{% block title %}Lineage Estimation{% endblock %}

{% block instructions %}
There are three ways to enter data for lineage estimation. It can either directly take the result of a state estimation (using the same user id), a table containing expression data, or the means and weights from state estimation. 
{% endblock %}

{% block method %}
Lineage estimation builds on top of the state estimation process. The cells which are closest to each cell type (identified from convex mixture parameters) are divided into separate sets and visualized in a two dimensional space. Each set is then fitted with a smooth curve to obtain within-cell-type lineages. These smooth curves are then joined with the closest curves, thereby completing the lineage tree construction. 
{% endblock %}


{% block input %}
    <form action="lineage/input" method="post" enctype=multipart/form-data>

        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <label for="useridinput">Enter a user id from a state estimation.</label>
                    <input type="text" id="useridinput" name="useridinput"></input>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default">Submit</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="form-group">
                        <label for="fileinput">Upload the data in as a tab-separated text file, where each row is a gene and each column is a cell.</label>
                        <input type="file" id="fileinput" name="fileinput"></input>
                    </div>
                    <div class="form-group">
                        <label for="k">Number of states (k):</label>
                        <input type=number id="k" name="k" value=2></input>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default">Submit Data</button>
                    </div>
                </div>
            </div>
        </div>


        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="form-group">
                        <label for="wfileinput">Upload W as a tab-separated text file.</label>
                        <input type="file" id="wfileinput" name="wfileinput"></input>
                    </div>
                    <div class="form-group">
                        <label for="mfileinput">Upload M as a tab-separated text file.</label>
                        <input type="file" id="mfileinput" name="mfileinput"></input>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default">Submit Data</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    {% endblock %}

uncurl_app/templates/lineage_user.html
{% extends "state_estimation_user.html" %}

{% block file_downloads %}
<p>
<a href="{{ user_id }}/m.txt">Centers</a>
</p>
<p>
<a href="{{ user_id }}/w.txt">Weights</a>
</p>
<p>
<a href="{{ user_id }}/smoothed_data.txt">Smoothed points</a>
</p>
<p>
<a href="{{ user_id }}/edges.txt">Edges</a>
</p>
<p>
<a href="{{ user_id }}/clusters.txt">Cluster assignments</a>
</p>
{% endblock %}

uncurl_app/templates/list_view.html
{% extends "base.html" %}

{% block title %}UNCURL{% endblock %}

{% block head %}
{{super()}}
{% endblock %}


{% block content %}

<div class="container container-main" role="main">

    <table>
        <tr><th>Test examples</th></tr>
        {% for element in test_dirs %}
        <tr><td><a href="user/{{ 'test_' + element }}/view">{{ element }}</a></td></tr>
        {% endfor %}
    </table>

    <table>
        <tr><th>User results</th></tr>
        {% for element in user_dirs %}
        <tr><td><a href="user/{{ element }}/view">{{ element }}</a></td></tr>
        {% endfor %}
    </table>

</div>

{% endblock %}

uncurl_app/templates/qual2quant_user.html
{% extends "state_estimation_user.html" %}

{% block file_downloads %}
<p>
<a href="{{ user_id }}/qual2quant_centers.txt">Centers</a>
</p>
{% endblock %}

uncurl_app/templates/report.html
{% extends "base.html" %}

{% block title %}UNCURL results - {{ user_id }}{% endblock %}

{% block head %}

<!-- TODO: have an option for serving static files?-->

<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>-->
<script src="{{ url_for('static', filename='popper.min.js') }}"></script>

{{ super() }}

<script src="{{ url_for('static', filename='jquery-3.3.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='plotly-latest.min.js') }}"></script>

<script>
// include data in this script
// TODO: this is probably kind of horrible...
var results = {{ results|safe }};
var all_query_ids = {{ cluster_ids|safe }};
var scatterplot_data = JSON.parse('{{ scatterplot|safe }}');
var top_genes = {{ top_genes|safe }};

function set_results_table(data, query_id) {
    // create table
    var results_view = $('#cellmesh_results_' + query_id);
    results_view.empty();
    results_view.append(`<div>Top cell type: ${data[1][1]}</div>`);
    var collapsible = $(`<a data-toggle="collapse" href="#table_${query_id}" aria-expanded="false" aria-controls="table_${query_id}">Show/hide all results</a>`);
    results_view.append(collapsible);
    var table = $(`<table class="collapse" id="table_${query_id}">`);
    var header = $('<tr>');
    for (var j = 0; j<data[0].length; j++) {
        header.append('<th>'+data[0][j]+'</th>');
    }
    table.append(header);
    for (var i = 1; i<data.length; i++) {
        var row = $('<tr>');
        for (var j = 0; j<data[i].length; j++) {
            row.append('<td>'+data[i][j]+'</td>');
        }
        table.append(row);
    }
    results_view.append(table);
    // add top genes
    var top_genes_view = $('#top_genes_' + query_id);
    for (var gene_id in top_genes[query_id]) {
        if (gene_id == 0) {
            top_genes_view.text(top_genes[query_id][gene_id]);
        } else {
            top_genes_view.text(top_genes_view.text() + ', ' + top_genes[query_id][gene_id]);
        }
    }
};

window.onload = function() {
    for (var id in all_query_ids) {
        set_results_table(results[id], id);
    }
    Plotly.newPlot("scatterplot", scatterplot_data.data, scatterplot_data.layout);
};


</script>

<link rel="stylesheet" href="{{ url_for('static', filename='state_estimation_style.css') }}" type="text/css"/>

{% endblock %}

{% block content %}

<div class="container container-main" role="main">
    <h3>Report for query id {{ user_id }}</h3>

    <div id="scatterplot" style="width: 800px;">
    </div>

    <div id="cellmesh_results">
        {% for cluster_id in cluster_ids %}
        <h4><b>Cluster {{ cluster_id }}</b></h4>
        <h5><b>Top Genes</b></h5>
        <div id="top_genes_{{ cluster_id }}"></div>
        <h5><b>Cell Types</b></h5>
        <div id="cellmesh_results_{{ cluster_id }}"></div>
        <hr/>
        {% endfor %}
    </div>
</div>

{% endblock %}